title: Katharina Blankart - Assistant Professor in Empirical Health Economics
author: katblankart
email: katharina.blankart@uni-due.de
description: > # this means to ignore newlines until "baseurl:"
  Economist, Master of Business Research, Health & Innovation, Pharmaceutical Markets

# social links
twitter_username: katblankart # DO NOT include the @ character, or else the build will fail!
github_username:  katblankart # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
